# Generated by Django 4.0.4 on 2022-04-24 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Candidate', '0001_initial'),
        ('Employee', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='applied_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candidate.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.job')),
            ],
        ),
    ]
