# Generated by Django 4.0.4 on 2022-04-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applying', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied_job',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
